services:
  db:
    container_name: dvdrental
    image: sensoteq/tech-assessment-db:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'dvdrental', '-U', 'postgres']
      interval: 10s
      retries: 5
      timeout: 5s

  server:
    container_name: express_server
    build: .
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/dvdrental
      - DB_HOST=db
      - DB_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
