 # web:
  #   container_name: server
  #   build: . 
  #   ports:
  #     - "8000:8000" 
  #   environment:
  #     - DATABASE_URL=postgres://postgres:postgres@dvdrental:5432/dvdrental 
  #     - PASSWORD=postgres
  #   depends_on:
  #     - db 

services:
  db:
    container_name: dvdrental
    image: sensoteq/tech-assessment-db:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 8080:5432

  pgadmin: 
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80

volumes:
  postgres_data:
